<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Regression &amp; Interpretability Challenge</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="index_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="index_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap-9e3ffae467580fdb927a41352e75a2e0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Regression &amp; Interpretability Challenge</h1>
<p class="subtitle lead">Don’t Trust Linear Models - The Perils of Non-Linearity</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="regression-challenge---linear-model-interpretability" class="level1">
<h1>Regression Challenge - Linear Model Interpretability</h1>
<section id="problem-violating-the-assumption-of-linearity" class="level2">
<h2 class="anchored" data-anchor-id="problem-violating-the-assumption-of-linearity">Problem Violating the Assumption of Linearity</h2>
<blockquote class="blockquote">
<p>“We need to stop believing much of the empirical work we’ve been doing.” - Christopher H. Achen</p>
</blockquote>
<p><strong>The Core Problem:</strong> When researchers need to ‘control for’ variables using linear regression, what happens when the relationships are non-linear?</p>
<p><strong>What does “control for” mean?</strong> Imagine you’re studying whether social media causes anxiety. You know that stress is a major cause of anxiety, and you also suspect that social media use might cause anxiety. So you need to “control for” stress to see if social media has an independent effect on anxiety. You want to ask: “If two people have the same stress level, does the one who uses more social media have higher anxiety?”</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>🎯 The Key Insight: Non-Linearity Breaks Even “Good” Regressions
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>The problem:</strong> Even when researchers carefully select control variables, non-linear relationships can make linear regression give completely wrong results.</p>
<p><strong>Why this matters:</strong> If non-linearity can break “proper” causal inference, imagine how much worse it gets when variables are added without careful thought (true “garbage can” regression).</p>
<p><strong>The connection:</strong> Both scenarios face the same fundamental challenge - linear regression assumes linearity, but real relationships rarely are.</p>
</div>
</div>
<p>Most researchers assume that if variables are “monotonically related” (meaning: as one variable goes up, the other always goes up or always goes down), then linear regression will give us the right answers. But here’s the catch: <strong>linearity is much stronger than monotonicity.</strong></p>
<ul>
<li><strong>Monotonicity:</strong> A one-unit increase in X always changes Y in the same direction</li>
<li><strong>Linearity:</strong> A one-unit increase in X always changes Y by the exact same amount</li>
</ul>
<p>In practice, we just assume linearity is “close enough” to monotonicity. But what if it’s not? What if even small amounts of non-linearity can make our regression results completely wrong?</p>
<p><strong>The Real-World Context:</strong> We know that stress is a major cause of anxiety, especially for college students. We also suspect that social media use might cause anxiety. So when we study this relationship, we need to control for stress to see the true effect of social media.</p>
<p><strong>The Key Problem:</strong> But here’s where things get tricky. In practice, we often can’t measure stress directly with expensive blood tests. Instead, we use surveys and self-reports. What happens when our “control variable” (stress) is measured imperfectly? What if the relationship between our proxy measure and the true stress level isn’t perfectly linear? This is exactly the kind of scenario where linear regression can lead us astray.</p>
<p><strong>The Devastating Reality:</strong> Even tiny amounts of non-linearity can completely destroy our regression conclusions. A relationship that looks “close enough” to linear can give us coefficients that are completely wrong: wrong signs, wrong magnitudes, wrong interpretations. The regression will confidently report statistically significant results that are fundamentally misleading about the true causal relationships.</p>
<p>Your challenge is to explore the simple example below and show how this happens:</p>
<p><span class="math display">\[
\begin{aligned}
A &amp;\equiv \textrm{Anxiety Level measured by fMRI activity}\\
S &amp;\equiv \textrm{Stress Level measured by cortisol level in blood}\\
T &amp;\equiv \textrm{\# of minutes on social media in last 24 hours}
\end{aligned}
\]</span></p>
<p>Let’s assume we <strong>know</strong> the relationship among these variables is as follows:</p>
<p><span class="math display">\[
Anxiety = Stress + 0.1 \times Time
\]</span></p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>🔍 Understanding the True Relationship: Implied Coefficients
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Critical Point:</strong> Students often miss that this specific equation implies specific coefficient values in the generic multiple regression framework.</p>
<p><strong>The Generic Multiple Regression Equation:</strong> <span class="math display">\[
Y = \beta_0 + \beta_1 X_1 + \beta_2 X_2 + \epsilon
\]</span></p>
<p><strong>In Our Case:</strong> <span class="math display">\[
Anxiety = \beta_0 + \beta_1 \times Stress + \beta_2 \times Time + \epsilon
\]</span></p>
<p><strong>The True Coefficients (what we “know”):</strong></p>
<ul>
<li><span class="math inline">\(\beta_0 = 0\)</span> (intercept is zero)</li>
<li><span class="math inline">\(\beta_1 = 1\)</span> (coefficient on Stress is 1)<br>
</li>
<li><span class="math inline">\(\beta_2 = 0.1\)</span> (coefficient on Time is 0.1)</li>
</ul>
<p><strong>Why This Matters:</strong> When we run regression analysis, we’re trying to estimate these <span class="math inline">\(\beta\)</span> coefficients. If our regression gives us coefficients that are very different from these true values, we know our model is wrong—even if it has good statistical fit!</p>
</div>
</div>
<section id="the-data-generation-process" class="level3">
<h3 class="anchored" data-anchor-id="the-data-generation-process">The Data Generation Process</h3>
<div class="cell" data-execution_count="2">
<div id="tbl-observations" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="2">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-observations-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Observed data with known true relationships
</figcaption>
<div aria-describedby="tbl-observations-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="2">
<div>


<table class="dataframe do-not-create-environment cell caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Stress</th>
<th data-quarto-table-cell-role="th">StressSurvey</th>
<th data-quarto-table-cell-role="th">Time</th>
<th data-quarto-table-cell-role="th">Anxiety</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>0</td>
<td>0</td>
<td>0.0</td>
<td>0.00</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>0</td>
<td>0</td>
<td>1.0</td>
<td>0.10</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>0</td>
<td>0</td>
<td>1.0</td>
<td>0.10</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>1</td>
<td>3</td>
<td>1.0</td>
<td>1.10</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>1</td>
<td>3</td>
<td>1.0</td>
<td>1.10</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>1</td>
<td>3</td>
<td>1.0</td>
<td>1.10</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">6</th>
<td>2</td>
<td>6</td>
<td>2.0</td>
<td>2.20</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">7</th>
<td>2</td>
<td>6</td>
<td>2.0</td>
<td>2.20</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">8</th>
<td>2</td>
<td>6</td>
<td>2.0</td>
<td>2.20</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">9</th>
<td>8</td>
<td>9</td>
<td>2.0</td>
<td>8.20</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">10</th>
<td>8</td>
<td>9</td>
<td>2.0</td>
<td>8.20</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">11</th>
<td>8</td>
<td>9</td>
<td>2.1</td>
<td>8.21</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">12</th>
<td>12</td>
<td>12</td>
<td>2.2</td>
<td>12.22</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">13</th>
<td>12</td>
<td>12</td>
<td>2.2</td>
<td>12.22</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">14</th>
<td>12</td>
<td>12</td>
<td>2.2</td>
<td>12.22</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
<p>Notice that <span class="math inline">\(Anxiety = Stress + 0.1 \times Time\)</span> indeed holds perfectly. Also, notice the addition of a <code>StressSurvey</code> column. This data was generated by a survey (instead of a blood test) to be a proxy for measuring stress levels using expensive and unpleasant blood tests. You can see it’s a good proxy as there is a <em>monotonic</em> (and a sorta-kinda <em>linear</em>) relationship between the survey results and actual measured stress levels (see <a href="#fig-stress-proxy" class="quarto-xref">Figure&nbsp;1</a>).</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>📝 Methodological Note: The Contrived Nature of This Example
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Important:</strong> This is a contrived example designed to illustrate the dangers of linear regression. In this simulation:</p>
<ul>
<li><strong>Blood test stress levels</strong> have a perfectly linear relationship with anxiety (by design)</li>
<li><strong>Survey stress responses</strong> have a non-linear relationship with anxiety (also by design)</li>
</ul>
<p>In the real world, there is no reason to believe linearity holds for either measurement method. Both blood tests and surveys would likely show non-linear relationships with anxiety. This example artificially creates the “perfect” scenario where one measurement is linear and the other is not, to demonstrate how regression can mislead us even when we think we’re controlling for the right variables.</p>
</div>
</div>
<div id="cell-fig-stress-proxy" class="cell" data-execution_count="3">
<div class="cell-output cell-output-display">
<div id="fig-stress-proxy" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-stress-proxy-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-stress-proxy-output-1.png" width="662" height="374" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-stress-proxy-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: StressSurvey as a proxy for actual Stress levels
</figcaption>
</figure>
</div>
</div>
</div>
<hr>
</section>
</section>
</section>
<section id="challenge-questions-and-answers" class="level1">
<h1>Challenge Questions and Answers</h1>
<section id="question-1-bivariate-regression-analysis-with-stresssurvey" class="level2">
<h2 class="anchored" data-anchor-id="question-1-bivariate-regression-analysis-with-stresssurvey">Question 1: Bivariate Regression Analysis with StressSurvey</h2>
<p><strong>Question:</strong> Run a bivariate regression of Anxiety on StressSurvey. What are the estimated coefficients? How do they compare to the true relationship?</p>
<div id="tbl-reg1" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="5">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-reg1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Bivariate Regression: Anxiety on StressSurvey
</figcaption>
<div aria-describedby="tbl-reg1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-stdout">
<pre><code>                            OLS Regression Results                            
==============================================================================
Dep. Variable:                Anxiety   R-squared:                       0.901
Model:                            OLS   Adj. R-squared:                  0.893
Method:                 Least Squares   F-statistic:                     118.4
Date:                Thu, 06 Nov 2025   Prob (F-statistic):           6.68e-08
Time:                        19:27:48   Log-Likelihood:                -27.079
No. Observations:                  15   AIC:                             58.16
Df Residuals:                      13   BIC:                             59.57
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
================================================================================
                   coef    std err          t      P&gt;|t|      [0.025      0.975]
--------------------------------------------------------------------------------
const           -1.5240      0.707     -2.156      0.050      -3.051       0.003
StressSurvey     1.0470      0.096     10.883      0.000       0.839       1.255
==============================================================================
Omnibus:                        2.125   Durbin-Watson:                   0.545
Prob(Omnibus):                  0.346   Jarque-Bera (JB):                1.642
Skew:                          -0.701   Prob(JB):                        0.440
Kurtosis:                       2.186   Cond. No.                         12.9
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.</code></pre>
</div>
</div>
</figure>
</div>
<p><strong>Answer:</strong></p>
<p>The bivariate regression of Anxiety on StressSurvey (shown in the table above) yields coefficients that differ substantially from the true relationship. The true relationship is <span class="math inline">\(Anxiety = Stress + 0.1 \times Time\)</span>, where the coefficient on Stress should be 1. However, when we regress Anxiety on StressSurvey alone, we obtain an intercept of <strong>-1.5240</strong> and a StressSurvey coefficient of <strong>1.0470</strong>, which is substantially different from the true Stress coefficient of 1.</p>
<p>This discrepancy occurs because StressSurvey is a proxy variable that has a non-linear relationship with the true Stress variable. While StressSurvey appears to be a good proxy (it shows a monotonic relationship), the non-linearity means that a simple linear regression on StressSurvey cannot recover the true relationship. The estimated coefficient of <strong>1.0470</strong> tells us that <strong>for each unit increase in StressSurvey, Anxiety increases by 1.0470 units</strong>, but this is not the same as the true effect of Stress on Anxiety (which should be 1.0).</p>
<p>Looking at the regression output, the StressSurvey coefficient has a p-value of <strong>0.000000</strong>, which is statistically significant (p &lt; 0.05). The R-squared value is <strong>0.9011</strong>, indicating that StressSurvey explains <strong>90.1%</strong> of the variation in Anxiety. However, these apparently “good” statistical properties mask the fundamental problem: the coefficient estimate is wrong because we’re using a non-linear proxy instead of the true variable.</p>
<hr>
</section>
<section id="question-2-visualization-of-bivariate-relationship-stresssurvey" class="level2">
<h2 class="anchored" data-anchor-id="question-2-visualization-of-bivariate-relationship-stresssurvey">Question 2: Visualization of Bivariate Relationship (StressSurvey)</h2>
<p><strong>Question:</strong> Create a scatter plot with the regression line showing the relationship between StressSurvey and Anxiety. Comment on the fit and any potential issues.</p>
<div id="cell-fig-stresssurvey-bivariate" class="cell" data-execution_count="7">
<div class="cell-output cell-output-display">
<div id="fig-stresssurvey-bivariate" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-stresssurvey-bivariate-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-stresssurvey-bivariate-output-1.png" width="758" height="469" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-stresssurvey-bivariate-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Scatter plot with regression line: Anxiety vs StressSurvey
</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Answer:</strong></p>
<p>The scatter plot reveals several important features of the relationship between StressSurvey and Anxiety:</p>
<ol type="1">
<li><p><strong>Overall Fit:</strong> The regression line appears to fit the data reasonably well, with an R-squared of <strong>0.9011</strong>, indicating that StressSurvey explains <strong>90.1%</strong> of the variation in Anxiety. The points generally follow a linear pattern, which initially suggests that StressSurvey is a good predictor of Anxiety.</p></li>
<li><p><strong>Potential Issues:</strong></p>
<ul>
<li><strong>Non-uniform distribution:</strong> The data points are not uniformly distributed across the StressSurvey range. There are clusters of observations at specific StressSurvey values (0, 3, 6, 9, 12), which suggests the relationship might be better understood as step-wise rather than truly linear.</li>
<li><strong>Possible non-linearity:</strong> While the overall trend is positive, the relationship between StressSurvey and Anxiety may not be perfectly linear. The regression line forces a linear relationship, but the underlying true relationship involves Stress (not StressSurvey) and Time.</li>
<li><strong>Missing variable bias:</strong> This bivariate regression omits Time, which is part of the true relationship. This omission could affect the coefficient estimate for StressSurvey.</li>
</ul></li>
<li><p><strong>Interpretation:</strong> The regression suggests that for each unit increase in StressSurvey, Anxiety increases by <strong>1.0470</strong> units. However, this coefficient of <strong>1.0470</strong> is misleading because it conflates the effects of Stress and Time, and because StressSurvey is a non-linear proxy for the true Stress variable. The true effect of Stress on Anxiety should be 1.0, but we’re getting <strong>1.0470</strong>, which is a difference of <strong>0.0470</strong> units. The visualization masks these problems behind an apparently clean linear fit.</p></li>
</ol>
<hr>
</section>
<section id="question-3-bivariate-regression-analysis-with-time" class="level2">
<h2 class="anchored" data-anchor-id="question-3-bivariate-regression-analysis-with-time">Question 3: Bivariate Regression Analysis with Time</h2>
<p><strong>Question:</strong> Run a bivariate regression of Anxiety on Time. What are the estimated coefficients? How do they compare to the true relationship?</p>
<div id="tbl-reg3" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="10">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-reg3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Bivariate Regression: Anxiety on Time
</figcaption>
<div aria-describedby="tbl-reg3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-stdout">
<pre><code>                            OLS Regression Results                            
==============================================================================
Dep. Variable:                Anxiety   R-squared:                       0.563
Model:                            OLS   Adj. R-squared:                  0.529
Method:                 Least Squares   F-statistic:                     16.75
Date:                Thu, 06 Nov 2025   Prob (F-statistic):            0.00127
Time:                        19:27:49   Log-Likelihood:                -38.223
No. Observations:                  15   AIC:                             80.45
Df Residuals:                      13   BIC:                             81.86
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P&gt;|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         -3.6801      2.233     -1.648      0.123      -8.504       1.144
Time           5.3406      1.305      4.093      0.001       2.522       8.160
==============================================================================
Omnibus:                        1.026   Durbin-Watson:                   0.661
Prob(Omnibus):                  0.599   Jarque-Bera (JB):                0.749
Skew:                          -0.162   Prob(JB):                        0.688
Kurtosis:                       1.955   Cond. No.                         5.80
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.</code></pre>
</div>
</div>
</figure>
</div>
<p><strong>Answer:</strong></p>
<p>The bivariate regression of Anxiety on Time (shown in the table above) yields a coefficient that is dramatically different from the true relationship. The true relationship is <span class="math inline">\(Anxiety = Stress + 0.1 \times Time\)</span>, where the coefficient on Time should be 0.1. However, when we regress Anxiety on Time alone, we obtain an intercept of <strong>-3.6801</strong> and a Time coefficient of <strong>5.3406</strong>, which is <strong>53.4</strong> times larger than the true Time coefficient of 0.1.</p>
<p>This large discrepancy occurs because Time is correlated with Stress in this dataset. When we omit Stress from the regression, the Time coefficient absorbs the effect of Stress, leading to a biased estimate. This is a classic example of <strong>omitted variable bias</strong>. The estimated coefficient of <strong>5.3406</strong> does not represent the true effect of Time on Anxiety (which should be 0.1), but rather the combined effect of Time and the omitted Stress variable.</p>
<p>The regression output shows that the Time coefficient has a p-value of <strong>0.001270</strong>, which is statistically significant (p &lt; 0.05). The R-squared value is <strong>0.5630</strong>, indicating that Time alone explains <strong>56.3%</strong> of the variation in Anxiety. This creates the dangerous illusion that social media use has a large effect on anxiety (<strong>5.3406</strong> units per unit increase in Time), when in reality, the true effect should only be 0.1 units per unit increase in Time. Most of this apparent effect is actually due to the omitted Stress variable.</p>
<hr>
</section>
<section id="question-4-visualization-of-bivariate-relationship-time" class="level2">
<h2 class="anchored" data-anchor-id="question-4-visualization-of-bivariate-relationship-time">Question 4: Visualization of Bivariate Relationship (Time)</h2>
<p><strong>Question:</strong> Create a scatter plot with the regression line showing the relationship between Time and Anxiety. Comment on the fit and any potential issues.</p>
<div id="cell-fig-time-bivariate" class="cell" data-execution_count="11">
<div class="cell-output cell-output-display">
<div id="fig-time-bivariate" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-time-bivariate-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-time-bivariate-output-1.png" width="758" height="469" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-time-bivariate-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Scatter plot with regression line: Anxiety vs Time
</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Answer:</strong></p>
<p>The scatter plot of Anxiety versus Time reveals several critical issues:</p>
<ol type="1">
<li><p><strong>Apparent Strong Relationship:</strong> The regression line suggests a strong positive relationship between Time and Anxiety, with a steep slope of <strong>5.3406</strong>. This creates the misleading impression that social media use has a large effect on anxiety. For each unit increase in Time, Anxiety increases by <strong>5.3406</strong> units according to this regression.</p></li>
<li><p><strong>Omitted Variable Problem:</strong> The scatter plot does not account for the confounding effect of Stress. In reality, both Time and Stress vary together in this dataset. Individuals with higher stress levels also tend to have slightly different Time values, and since Stress has a large effect on Anxiety (coefficient = 1), the regression incorrectly attributes this effect to Time.</p></li>
<li><p><strong>Clustering Pattern:</strong> The data points show clustering patterns that suggest the relationship is driven more by Stress levels than by Time. The wide vertical spread at similar Time values indicates that other factors (namely Stress) are driving the variation in Anxiety.</p></li>
<li><p><strong>Misleading Fit:</strong> Despite a high R-squared of <strong>0.5630</strong>, this regression is fundamentally misleading. The high R-squared is achieved because Time is correlated with Stress, but the coefficient on Time (<strong>5.3406</strong>) is <strong>53.4</strong> times larger than the true coefficient of 0.1. The difference is <strong>5.2406</strong> units.</p></li>
<li><p><strong>Interpretation:</strong> If a researcher published this result, they might conclude that social media use increases anxiety by <strong>5.3406</strong> units per unit increase in Time, when the true effect should only be 0.1 units. This is a dangerous conclusion that could lead to incorrect policy recommendations or public health advice. The visualization and regression statistics create a compelling but false narrative about the relationship between social media and anxiety.</p></li>
</ol>
<hr>
</section>
<section id="question-5-multiple-regression-analysis-stresssurvey-and-time" class="level2">
<h2 class="anchored" data-anchor-id="question-5-multiple-regression-analysis-stresssurvey-and-time">Question 5: Multiple Regression Analysis (StressSurvey and Time)</h2>
<p><strong>Question:</strong> Run a multiple regression of Anxiety on both <strong>StressSurvey</strong> and Time. What are the estimated coefficients? How do they compare to the true relationship?</p>
<div id="tbl-reg5" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="15">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-reg5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4: Multiple Regression: Anxiety on StressSurvey and Time
</figcaption>
<div aria-describedby="tbl-reg5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-stdout">
<pre><code>                            OLS Regression Results                            
==============================================================================
Dep. Variable:                Anxiety   R-squared:                       0.935
Model:                            OLS   Adj. R-squared:                  0.924
Method:                 Least Squares   F-statistic:                     86.32
Date:                Thu, 06 Nov 2025   Prob (F-statistic):           7.54e-08
Time:                        19:27:49   Log-Likelihood:                -23.931
No. Observations:                  15   AIC:                             53.86
Df Residuals:                      12   BIC:                             55.99
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
================================================================================
                   coef    std err          t      P&gt;|t|      [0.025      0.975]
--------------------------------------------------------------------------------
const            0.5888      1.034      0.569      0.580      -1.664       2.841
StressSurvey     1.4269      0.172      8.287      0.000       1.052       1.802
Time            -2.7799      1.111     -2.502      0.028      -5.201      -0.359
==============================================================================
Omnibus:                        1.255   Durbin-Watson:                   1.043
Prob(Omnibus):                  0.534   Jarque-Bera (JB):                1.051
Skew:                           0.546   Prob(JB):                        0.591
Kurtosis:                       2.302   Cond. No.                         31.9
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.</code></pre>
</div>
</div>
</figure>
</div>
<p><strong>Answer:</strong></p>
<p>The multiple regression of Anxiety on both StressSurvey and Time (shown in the table above) yields coefficients that differ from the true relationship. The true relationship is <span class="math inline">\(Anxiety = Stress + 0.1 \times Time\)</span>, which implies: - True intercept = 0 - True Stress coefficient = 1 - True Time coefficient = 0.1</p>
<p><strong>Results Analysis:</strong></p>
<ol type="1">
<li><p><strong>Intercept:</strong> The estimated intercept is <strong>0.5888</strong>, which deviates from the true value of 0 by <strong>0.5888</strong> units.</p></li>
<li><p><strong>StressSurvey Coefficient:</strong> The estimated coefficient on StressSurvey is <strong>1.4269</strong>, which differs from the true Stress coefficient of 1 by <strong>0.4269</strong> units. This occurs because StressSurvey is a non-linear proxy for Stress. While StressSurvey is monotonically related to Stress, the non-linearity means that the linear regression cannot recover the true coefficient.</p></li>
<li><p><strong>Time Coefficient:</strong> The estimated coefficient on Time is <strong>-2.7799</strong>, which differs from the true value of 0.1 by <strong>2.8799</strong> units. This is particularly concerning because it suggests that even after “controlling for” StressSurvey, we get incorrect estimates of Time’s effect on Anxiety. The coefficient has <strong>the wrong sign</strong> compared to the true positive value of 0.1.</p></li>
<li><p><strong>Statistical Significance:</strong> The StressSurvey coefficient has a p-value of <strong>0.000003</strong> and the Time coefficient has a p-value of <strong>0.027816</strong>. <strong>Both coefficients are statistically significant</strong> (p &lt; 0.05). However, statistical significance does not guarantee correct coefficients.</p></li>
<li><p><strong>Model Fit:</strong> The R-squared is <strong>0.9350</strong>, indicating that the model explains <strong>93.5%</strong> of the variation in Anxiety. However, the high R-squared does not mean the coefficients are correct—they are still biased due to the non-linear relationship between StressSurvey and Stress.</p></li>
</ol>
<p><strong>Key Insight:</strong> This regression demonstrates a critical problem: even when we “control for” variables using multiple regression, if our control variable (StressSurvey) is a non-linear proxy for the true variable (Stress), we cannot recover the true coefficients. The regression gives us statistically significant results that are fundamentally misleading.</p>
<hr>
</section>
<section id="question-6-multiple-regression-analysis-stress-and-time" class="level2">
<h2 class="anchored" data-anchor-id="question-6-multiple-regression-analysis-stress-and-time">Question 6: Multiple Regression Analysis (Stress and Time)</h2>
<p><strong>Question:</strong> Run a multiple regression of Anxiety on both <strong>Stress</strong> and Time. What are the estimated coefficients? How do they compare to the true relationship?</p>
<div id="tbl-reg6" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="18">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-reg6-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5: Multiple Regression: Anxiety on Stress and Time
</figcaption>
<div aria-describedby="tbl-reg6-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-stdout">
<pre><code>                            OLS Regression Results                            
==============================================================================
Dep. Variable:                Anxiety   R-squared:                       1.000
Model:                            OLS   Adj. R-squared:                  1.000
Method:                 Least Squares   F-statistic:                 8.600e+31
Date:                Thu, 06 Nov 2025   Prob (F-statistic):          1.15e-187
Time:                        19:27:49   Log-Likelihood:                 493.62
No. Observations:                  15   AIC:                            -981.2
Df Residuals:                      12   BIC:                            -979.1
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P&gt;|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        1.11e-16   1.02e-15      0.109      0.915   -2.11e-15    2.34e-15
Stress         1.0000   1.15e-16   8.67e+15      0.000       1.000       1.000
Time           0.1000   8.12e-16   1.23e+14      0.000       0.100       0.100
==============================================================================
Omnibus:                        3.041   Durbin-Watson:                   0.639
Prob(Omnibus):                  0.219   Jarque-Bera (JB):                1.362
Skew:                           0.357   Prob(JB):                        0.506
Kurtosis:                       1.709   Cond. No.                         23.9
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.</code></pre>
</div>
</div>
</figure>
</div>
<p><strong>Answer:</strong></p>
<p>The multiple regression of Anxiety on both Stress and Time (shown in the table above) recovers the true coefficients almost perfectly. The true relationship is <span class="math inline">\(Anxiety = Stress + 0.1 \times Time\)</span>, which implies: - True intercept = 0 - True Stress coefficient = 1 - True Time coefficient = 0.1</p>
<p><strong>Results Analysis:</strong></p>
<ol type="1">
<li><p><strong>Intercept:</strong> The estimated intercept is <strong>0.000000</strong>, which is essentially zero (deviating from 0 by only <strong>0.000000</strong> units), matching the true relationship perfectly.</p></li>
<li><p><strong>Stress Coefficient:</strong> The estimated coefficient on Stress is <strong>1.0000</strong>, which differs from the true value of 1 by only <strong>0.000000</strong> units, matching the true relationship perfectly.</p></li>
<li><p><strong>Time Coefficient:</strong> The estimated coefficient on Time is <strong>0.1000</strong>, which differs from the true value of 0.1 by only <strong>0.000000</strong> units, matching the true relationship perfectly.</p></li>
<li><p><strong>Statistical Significance:</strong> The Stress coefficient has a p-value of <strong>3.737032e-186</strong> and the Time coefficient has a p-value of <strong>5.563718e-164</strong>. Both coefficients are highly statistically significant (p &lt; 0.001).</p></li>
<li><p><strong>Model Fit:</strong> The R-squared is <strong>1.000000</strong>, indicating perfect (or near-perfect) fit, which makes sense given that the data was generated from this exact relationship.</p></li>
</ol>
<p><strong>Key Insight:</strong> When we use the true Stress variable (measured by blood test) instead of the StressSurvey proxy, the multiple regression recovers the true coefficients almost perfectly. This demonstrates that the problem in the previous regression (Question 5) was not with the regression technique itself, but with using a non-linear proxy variable (StressSurvey) instead of the true variable (Stress). This is the crucial lesson: the quality of measurement matters enormously. Using the true variable gives correct results, while using even a “good” proxy can give completely wrong results.</p>
<hr>
</section>
<section id="question-7-model-comparison" class="level2">
<h2 class="anchored" data-anchor-id="question-7-model-comparison">Question 7: Model Comparison</h2>
<p><strong>Question:</strong> Compare the R-squared values and coefficient interpretations between the two multiple regression models. Do both models show statistical significance in all of their coefficient estimates? What does this tell you about the real-world implications of multiple regression results?</p>
<div id="tbl-model-comparison" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="19">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-model-comparison-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6: Comparison of Multiple Regression Models
</figcaption>
<div aria-describedby="tbl-model-comparison-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-stdout">
<pre><code>                       Model  R-squared    Intercept  Stress/StressSurvey Coef  Time Coef  Stress/StressSurvey p-value  Time p-value
Model 1: StressSurvey + Time   0.935005 5.887578e-01                  1.426926  -2.779944                 2.615836e-06  2.781595e-02
      Model 2: Stress + Time   1.000000 1.110223e-16                  1.000000   0.100000                3.737032e-186 5.563718e-164</code></pre>
</div>
</div>
</figure>
</div>
<div id="cell-fig-coefficient-comparison" class="cell" data-execution_count="20">
<div class="cell-output cell-output-display">
<div id="fig-coefficient-comparison" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-coefficient-comparison-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-coefficient-comparison-output-1.png" width="1430" height="373" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-coefficient-comparison-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Comparison of Estimated Coefficients vs True Coefficients
</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Answer:</strong></p>
<p><strong>Model Comparison Summary:</strong></p>
<p>Both models show statistical significance (p &lt; 0.05) for all coefficients, as shown in the regression tables and comparison table above. However, the coefficients tell very different stories:</p>
<p><strong>Key Findings:</strong></p>
<ol type="1">
<li><p><strong>R-squared Comparison:</strong> Model 1 has an R-squared of <strong>0.9350</strong>, while Model 2 has an R-squared of <strong>1.000000</strong>. Both models have high R-squared values, with Model 2 achieving perfect (or near-perfect) fit. Model 1 also has a high R-squared, which is misleading—it suggests the model fits well, but the coefficients are wrong. This demonstrates that high R-squared does not guarantee correct coefficients.</p></li>
<li><p><strong>Coefficient Accuracy:</strong></p>
<ul>
<li><strong>Model 1 (StressSurvey):</strong> The StressSurvey coefficient is <strong>1.4269</strong>, which differs from the true value of 1 by <strong>0.4269</strong> units. The Time coefficient is <strong>-2.7799</strong>, which differs from the true value of 0.1 by <strong>2.8799</strong> units and has <strong>the wrong sign</strong>.</li>
<li><strong>Model 2 (Stress):</strong> The Stress coefficient is <strong>1.0000</strong>, which is essentially equal to the true value of 1 (difference: <strong>0.000000</strong>), and the Time coefficient is <strong>0.1000</strong>, which is essentially equal to the true value of 0.1 (difference: <strong>0.000000</strong>).</li>
</ul></li>
<li><p><strong>The Deceptive Nature of Statistical Significance:</strong> Both models report statistically significant coefficients (Model 1: StressSurvey p = <strong>0.000003</strong>, Time p = <strong>0.027816</strong>; Model 2: Stress p = <strong>3.737032e-186</strong>, Time p = <strong>5.563718e-164</strong>), but only Model 2 has the correct coefficients. This demonstrates that <strong>statistical significance does not guarantee correct coefficients</strong>. A model can be statistically significant and still be fundamentally wrong.</p></li>
</ol>
<p><strong>Real-World Implications:</strong></p>
<ol type="1">
<li><p><strong>The Proxy Variable Problem:</strong> In real research, we often cannot measure variables directly. We use proxies (like surveys instead of blood tests). This analysis shows that even “good” proxies (monotonic relationships) can lead to completely wrong conclusions if they have non-linear relationships with the true variables.</p></li>
<li><p><strong>The Illusion of Control:</strong> Researchers often believe that including control variables in multiple regression solves confounding problems. However, if those control variables are imperfect proxies, the regression can still give misleading results—even with high R-squared and statistical significance.</p></li>
<li><p><strong>Policy and Public Health Implications:</strong> If Model 1 were published, it could lead to incorrect conclusions about the relationship between social media use and anxiety. Researchers might recommend policies based on the wrong coefficient estimates, wasting resources or even causing harm.</p></li>
<li><p><strong>The Importance of Measurement Quality:</strong> This analysis highlights that the quality of measurement matters enormously. Using the true Stress variable (blood test) gives correct results, while using the StressSurvey proxy gives misleading results, even though both are highly correlated and statistically significant.</p></li>
<li><p><strong>Trust but Verify:</strong> Researchers should never trust regression results based solely on statistical significance and R-squared. They must:</p>
<ul>
<li>Question the quality of proxy variables</li>
<li>Check for non-linear relationships</li>
<li>Validate results against theoretical expectations</li>
<li>Consider alternative specifications</li>
<li>Use graphical diagnostics to detect problems</li>
</ul></li>
</ol>
<hr>
</section>
<section id="question-8-reflect-on-real-world-implications" class="level2">
<h2 class="anchored" data-anchor-id="question-8-reflect-on-real-world-implications">Question 8: Reflect on Real-World Implications</h2>
<p><strong>Question:</strong> For each of the two multiple regression models, assume their respective outputs/conclusions were published in academic journals and then subsequently picked up by the popular press. What headline about time spent on social media and its effect on anxiety would you expect to see from a popular press outlet covering the first model? And what headline would you expect to see from a popular press outlet covering the second model? Assuming confirmation bias is real, which model is a typical parent going to believe? Which model will Facebook, Instagram, and TikTok executives prefer?</p>
<p><strong>Answer:</strong></p>
<p><strong>Headline for Model 1 (StressSurvey + Time):</strong></p>
<p>Based on Model 1, which shows a Time coefficient of <strong>-2.7799</strong> (dramatically different from the true value of 0.1), a popular press outlet might run a headline like:</p>
<blockquote class="blockquote">
<p><strong>“Surprising Study: Social Media Use May Reduce Anxiety, Researchers Find”</strong></p>
<p><em>Contrary to popular belief, new research suggests that social media use might actually lower anxiety levels when stress is accounted for.</em></p>
</blockquote>
<p><strong>Headline for Model 2 (Stress + Time):</strong></p>
<p>Based on Model 2, which shows the correct Time coefficient of <strong>0.1000</strong>, a popular press outlet might run a headline like:</p>
<blockquote class="blockquote">
<p><strong>“Social Media’s Effect on Anxiety is Modest, New Study Shows”</strong></p>
<p><em>Research using precise stress measurements finds that social media use has a small but measurable effect on anxiety levels.</em></p>
</blockquote>
<p>Or, given the small coefficient (0.1):</p>
<blockquote class="blockquote">
<p><strong>“Study: Stress, Not Social Media, is Primary Driver of Anxiety”</strong></p>
<p><em>New research using blood test data reveals that stress levels are the main factor in anxiety, with social media use playing only a minor role.</em></p>
</blockquote>
<p><strong>Confirmation Bias and Parental Beliefs:</strong></p>
<p>A typical parent, concerned about their child’s screen time and anxiety, would likely <strong>believe Model 1</strong> if it showed a large positive effect, because:</p>
<ol type="1">
<li><p><strong>Confirmation Bias:</strong> Parents who are already worried about social media might initially be surprised by Model 1’s negative coefficient (<strong>-2.7799</strong>), but since it contradicts their beliefs, they may question the methodology or look for other studies. However, if Model 1 showed a large positive effect, they would find it more credible than Model 2’s finding of a small effect (coefficient = <strong>0.1000</strong>).</p></li>
<li><p><strong>Emotional Appeal:</strong> Headlines about “dramatic increases” in anxiety are more emotionally compelling than nuanced findings about “modest effects.” Parents are more likely to share and remember alarming headlines.</p></li>
<li><p><strong>Simplistic Explanations:</strong> Model 1 (if it shows a large effect) offers a simple explanation: “Social media causes anxiety.” This is easier to understand and act upon than Model 2’s more complex message: “Stress is the main driver, and social media has a small additional effect.”</p></li>
<li><p><strong>Actionable Advice:</strong> If Model 1 suggests limiting social media will dramatically reduce anxiety, parents have a clear action plan. Model 2’s message that stress management is more important is less immediately actionable.</p></li>
</ol>
<p><strong>Social Media Executives’ Preferences:</strong></p>
<p>Facebook, Instagram, and TikTok executives would <strong>strongly prefer Model 2</strong> (the correct model) because:</p>
<ol type="1">
<li><p><strong>Minimal Blame:</strong> Model 2 shows that social media has only a small effect (coefficient = <strong>0.1000</strong>) compared to stress (coefficient = <strong>1.0000</strong>). This allows executives to argue that their platforms are not the primary cause of anxiety—stress is.</p></li>
<li><p><strong>Defensive Strategy:</strong> Executives can point to Model 2 and say: “See, our research shows that social media has a minimal effect on anxiety. The real problem is stress in people’s lives, which we cannot control.”</p></li>
<li><p><strong>Regulatory Avoidance:</strong> If Model 2 is accepted, there is less pressure for regulation. Policymakers are less likely to impose strict regulations on platforms that have only a small effect on mental health.</p></li>
<li><p><strong>Public Relations:</strong> Model 2 allows executives to position their companies as responsible actors who are addressing a real but small problem, rather than major contributors to a mental health crisis.</p></li>
</ol>
<p><strong>The Danger:</strong></p>
<p>This scenario illustrates a critical problem in how research is communicated and used:</p>
<ol type="1">
<li><p><strong>The Wrong Model Can Win:</strong> If Model 1 (the incorrect model) is published first or gets more media attention, it can become the “accepted truth” even if Model 2 (the correct model) is published later. Once public opinion is formed, it is difficult to change.</p></li>
<li><p><strong>Stakeholders Choose Their Truth:</strong> Different stakeholders will gravitate toward the model that supports their existing beliefs or interests. Parents worried about social media will believe Model 1; executives will promote Model 2.</p></li>
<li><p><strong>The Importance of Methodological Transparency:</strong> This analysis highlights why researchers must be transparent about their measurement methods. If readers knew that Model 1 used survey proxies while Model 2 used precise blood tests, they could better evaluate which model to trust.</p></li>
<li><p><strong>The Role of Peer Review:</strong> Peer reviewers should carefully examine the quality of proxy variables and the potential for non-linear relationships. However, this analysis shows that even models with high R-squared and statistical significance can be fundamentally wrong if they use imperfect proxies.</p></li>
</ol>
<hr>
</section>
<section id="question-9-avoiding-misleading-statistical-significance" class="level2">
<h2 class="anchored" data-anchor-id="question-9-avoiding-misleading-statistical-significance">Question 9: Avoiding Misleading Statistical Significance</h2>
<p><strong>Question:</strong> Reflect on this tip to avoid being misled by statistically significant results: splitting the sample into meaningful subsets (“statistical regimes”), and using graphical diagnostics for linearity rather than blind reliance on “canned” regressions. Apply this approach to multiple regression of Anxiety on both StressSurvey and Time by analyzing a smartly chosen subset of the data. What specific subset did you choose and why? Did you get results that are both statistically significant and close to the true relationship?</p>
<p><strong>Answer:</strong></p>
<p><strong>Identifying Statistical Regimes:</strong></p>
<p>Looking at the data, I notice that the Stress variable has distinct “regimes”: - <strong>Low Stress Regime:</strong> Stress = 0, 1, 2 (lower stress levels) - <strong>High Stress Regime:</strong> Stress = 8, 12 (higher stress levels)</p>
<p>The relationship between StressSurvey and Stress appears to be more linear within each regime than across regimes. I chose to analyze the low-stress subset (Stress ≤ 2) where the relationship should be more stable and where we avoid the major non-linear jump that occurs when Stress moves from 2 to 8.</p>
<div id="fig-subset-analysis" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="24">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-subset-analysis-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-stdout">
<pre><code>================================================================================
SUBSET ANALYSIS: Low Stress Regime (Stress ≤ 2)
================================================================================
Number of observations: 9

Regression Results:
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                Anxiety   R-squared:                       1.000
Model:                            OLS   Adj. R-squared:                  1.000
Method:                 Least Squares   F-statistic:                 5.366e+30
Date:                Thu, 06 Nov 2025   Prob (F-statistic):           1.75e-91
Time:                        19:27:50   Log-Likelihood:                 301.93
No. Observations:                   9   AIC:                            -597.9
Df Residuals:                       6   BIC:                            -597.3
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
================================================================================
                   coef    std err          t      P&gt;|t|      [0.025      0.975]
--------------------------------------------------------------------------------
const         2.887e-16   6.31e-16      0.458      0.663   -1.26e-15    1.83e-15
StressSurvey     0.3333   2.17e-16   1.53e+15      0.000       0.333       0.333
Time             0.1000   8.46e-16   1.18e+14      0.000       0.100       0.100
==============================================================================
Omnibus:                        7.901   Durbin-Watson:                   0.278
Prob(Omnibus):                  0.019   Jarque-Bera (JB):                2.800
Skew:                          -1.261   Prob(JB):                        0.247
Kurtosis:                       4.051   Cond. No.                         15.8
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
================================================================================

True Coefficients: Intercept = 0, Stress = 1, Time = 0.1
Estimated Coefficients: Intercept = 0.0000, StressSurvey = 0.3333, Time = 0.1000
================================================================================</code></pre>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-subset-analysis-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5
</figcaption>
</figure>
</div>
<div id="cell-fig-subset-visualization" class="cell" data-execution_count="25">
<div class="cell-output cell-output-display">
<div id="fig-subset-visualization" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-subset-visualization-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-subset-visualization-output-1.png" width="1334" height="470" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-subset-visualization-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: Visualization: StressSurvey vs Anxiety in Low Stress Regime
</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Analysis of Subset Results:</strong></p>
<p><strong>Answer:</strong></p>
<p><strong>Subset Chosen:</strong> Low Stress Regime (Stress ≤ 2), which includes <strong>9</strong> observations from the original dataset.</p>
<p><strong>Rationale for This Subset:</strong></p>
<ol type="1">
<li><p><strong>Reduced Non-linearity:</strong> Within the low-stress regime, the relationship between StressSurvey and Stress is more linear. The non-linear jump occurs when Stress moves from 2 to 8, so by focusing on the low-stress subset, we avoid the major non-linearity.</p></li>
<li><p><strong>More Homogeneous Group:</strong> The low-stress subset represents a more homogenous group where the relationship between variables should be more stable and interpretable.</p></li>
<li><p><strong>Statistical Regime Concept:</strong> This subset represents a distinct “statistical regime” where the underlying relationships might be more consistent.</p></li>
</ol>
<p><strong>Results:</strong></p>
<p>The subset regression results are shown in the output above. The regression yields: - <strong>Intercept:</strong> <strong>0.0000</strong> (True: 0, difference: <strong>0.0000</strong>) - <strong>StressSurvey Coefficient:</strong> <strong>0.3333</strong> (True Stress coefficient: 1, difference: <strong>0.6667</strong>) - <strong>Time Coefficient:</strong> <strong>0.1000</strong> (True: 0.1, difference: <strong>0.0000</strong>)</p>
<p><strong>Statistical Significance:</strong></p>
<p>The StressSurvey coefficient has a p-value of <strong>0.000000</strong>, which is <strong>statistically significant</strong> (p &lt; 0.05). The Time coefficient has a p-value of <strong>0.000000</strong>, which is <strong>statistically significant</strong> (p &lt; 0.05).</p>
<p><strong>Evaluation:</strong></p>
<p>The subset analysis shows <strong>improved</strong> results compared to the full model. The Time coefficient in the subset (<strong>0.1000</strong>) is <strong>closer to</strong> the true value of 0.1 than the full model coefficient (<strong>-2.7799</strong>). However, the StressSurvey coefficient (<strong>0.3333</strong>) still differs from the true Stress coefficient of 1 by <strong>0.6667</strong> units because even within this subset, StressSurvey remains a proxy variable with a non-linear relationship to the true Stress variable.</p>
<p><strong>Key Insights:</strong></p>
<ol type="1">
<li><p><strong>Subset Analysis Helps But Doesn’t Solve Everything:</strong> Splitting the sample into meaningful subsets can improve coefficient estimates by reducing non-linearity within each regime. However, it cannot fully solve the problem if the proxy variable (StressSurvey) is fundamentally different from the true variable (Stress). The subset model achieves an R-squared of <strong>1.0000</strong>, compared to the full model’s R-squared of <strong>0.9350</strong>.</p></li>
<li><p><strong>The Importance of Graphical Diagnostics:</strong> Before running regressions, researchers should plot the data to identify distinct regimes, non-linear patterns, and potential subset analyses. This graphical exploration can reveal problems that automated regression procedures might miss.</p></li>
<li><p><strong>Limitations of Subset Analysis:</strong></p>
<ul>
<li><strong>Reduced Sample Size:</strong> The subset has only <strong>9</strong> observations (compared to 15 in the full dataset), which reduces statistical power and increases uncertainty.</li>
<li><strong>Proxy Variable Problem Persists:</strong> Even within the subset, StressSurvey is still not the true Stress variable, so the coefficient (<strong>0.3333</strong>) cannot perfectly match the true relationship (coefficient = 1). The difference is <strong>0.6667</strong> units.</li>
<li><strong>Generalizability:</strong> Results from a subset may not generalize to the full population.</li>
</ul></li>
<li><p><strong>Best Practices:</strong></p>
<ul>
<li><strong>Visualize First:</strong> Always plot your data to identify regimes and non-linear patterns.</li>
<li><strong>Question Your Proxies:</strong> Be skeptical of proxy variables, even if they seem correlated with true variables.</li>
<li><strong>Test Across Regimes:</strong> If you identify regimes, test whether relationships hold consistently across them.</li>
<li><strong>Report Limitations:</strong> Be transparent about the limitations of subset analyses and proxy variables.</li>
</ul></li>
</ol>
<p><strong>Conclusion:</strong></p>
<p>While subset analysis can improve results by focusing on more homogeneous groups, it does not fully solve the problem of using imperfect proxy variables. The best solution is to use the true variable (Stress from blood tests) whenever possible. When proxies must be used, researchers should: 1. Acknowledge the limitations 2. Use graphical diagnostics to identify problems 3. Consider subset analyses within distinct regimes 4. Interpret results with appropriate skepticism 5. Validate findings against theoretical expectations</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>